apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tempo

helmCharts:
  - name: tempo-distributed
    path: tempo-chart
    valuesInline:
      replicaCount: 3
      storage:
        enabled: true
        size: 10Gi


resources:
  - tempo-datasource.yaml
